---
- name: create ansible group
  group: >
    name=ansible

- name: Create ansible user
  user: >
    name=ansible
    group=ansible
    groups=wheel
    shell=/bin/bash
    comment="Ansible created"

- name: update user authorized_keys
  authorized_key: >
      user=ansible
      key="{{ item }}"
  with_file:
      - files/ssh_keys/authorized_keys